# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fyg_rit_orig <- function(surv_cens, beta_res, x_mat) {
    .Call('rankAFT_fyg_rit_orig', PACKAGE = 'rankAFT', surv_cens, beta_res, x_mat)
}

fyg_rit_smooth <- function(surv_cens, beta_res, x_mat, h) {
    .Call('rankAFT_fyg_rit_smooth', PACKAGE = 'rankAFT', surv_cens, beta_res, x_mat, h)
}

A_n_calc <- function(surv_cens, beta_res, x_mat, h) {
    .Call('rankAFT_A_n_calc', PACKAGE = 'rankAFT', surv_cens, beta_res, x_mat, h)
}

V_n_calc <- function(surv_cens, beta_res, x_mat, h) {
    .Call('rankAFT_V_n_calc', PACKAGE = 'rankAFT', surv_cens, beta_res, x_mat, h)
}

